name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up virtual environment
      uses: actions/virtual-environments@v3
      with:
        python-version: ${{ matrix.python-version }}
        name: Arvello # specify the name of the virtual environment
    - name: Activate virtual environment
      run: source ${{ env.PYTHON_VIRTUAL_ENV }}/bin/activate
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Django
    - name: Run Test
      run: |
        python manage.py test
